#!/bin/bash
cd /tmp
su -c 'dnf install nmap vim wget -y'
wget -O splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-x86_64.rpm 'https://d7wz6hmoaavd0.cloudfront.net/products/universalforwarder/releases/8.2.1/linux/splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-x86_64.rpm'
su -c 'dnf install splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-x86_64.rpm -y'

su -c 'cat <<EOT >> /opt/splunkforwarder/etc/system/local/user-seed.conf
[user_info]
USERNAME = admin
PASSWORD = splunk123!
EOT
'

su -c 'ln -s /opt/splunkforwarder/bin/splunk /usr/bin/splunk'

su -c '/opt/splunkforwarder/bin/splunk restart --accept-license --answer-yes --no-prompt'
su -c '/opt/splunkforwarder/bin/splunk add forward-server splunk:9997 -auth admin:splunk123!'
su -c '/opt/splunkforwarder/bin/splunk add monitor /var/log/messages'
su -c '/opt/splunkforwarder/bin/splunk add monitor /etc/sudoers'