---
- name: configure splunk es 
  hosts: splunkvm
  gather_facts: false
  become: yes

  collections:
     - awx.awx
     - splunk.es

  tasks:
      
    - name: install some programs
      dnf:
        name:
          - nano
          - nmap
          - vim
          - wget
          - lsof
        state: present

    

    - name: install splunk es
      dnf:
        name: https://d7wz6hmoaavd0.cloudfront.net/products/splunk/releases/8.2.2/linux/splunk-8.2.2-87344edfcdb4-linux-2.6-x86_64.rpm
        disable_gpg_check: true
        state: present

    - name: create symlink to splunk binary
      ansible.builtin.file:
        src: /opt/splunk/bin/splunk
        dest: /usr/bin/splunk
        state: link

    - name: copy user-seed.conf 
      copy:
        src: files/user-seed.conf
        dest: /opt/splunk/etc/system/local/user-seed.conf
      
    - name: configure splunk  - accept license and set user/password
      shell: /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt || /bin/true
    


