- name: restore original sudoers file
  hosts: rhel
  gather_facts: false
  become: yes

  tasks:
  
    - name: make sure sudoers file is not open before continuing
      shell: lsof -t /etc/sudoers
      register: file_open
      until: file_open.stdout == ""
      delay: 10
      
    - name: copy original sudoers to rhel vms
      copy: 
        src: ./files/sudoers
        dest: /etc/sudoers
  
