#!/bin/bash

## Sleep 5 seconds so vm is completely up
sleep 5

## make sudo no password for rhel user
## su -c "sed -i 's/#%wheel/%wheel/g' /etc/sudoers
su -c 'usermod -aG wheel rhel'

## disable ansible host key checking
su -c "sed -i 's/#host_key_checking/host_key_checking/g' /etc/ansible/ansible.cfg

## install ansible collections
su -c 'ansible-galaxy collection install splunk.es awx.awx'

## clone repo and run startup script.  
su -c 'git clone https://github.com/gejames/splunk-demo /home/rhel/splunk-demo'
cd /home/rhel/splunk-demo
su -c 'ansible-playbook rhelvm_start.yml  -i hosts'